config:
  name: 'Testando o teste ?'
  nasmDir: 'assembly'
  hackDir: 'hack'
  tstDir: 'tests'

not_working:

- vectorMean
- factorial

test_files:
- add
- sub
- mov
- abs
- max
- mult
- mod
- div
- isEven
- pow
- stringLength
- palindromo
