config:
  type: "vm"
  name: "Teste VM"
  vmDir: "vm/examples"
  nasmDir: "vm-nasm"
  hackDir: "vm-hack"
  tstDir: "tests_vm"

not_working:
  - SimplePushConst.vm
  - SimplePushLocal.vm
  - SimplePushTemp.vm
  - SimplePushThat.vm
  - SimplePushThis.vm
  - SimplePopLocal.vm
  - SimplePopPointer.vm
  - SimplePopThat.vm
  - SimplePopThis.vm
  - SimplePushAdd.vm
  - SimplePushArg.vm
  - SimpleGoto.vm
  - SimpleIfGoto.vm
  - StackTest.vm
  - StaticTest.vm
  - SimpleFunction
  - Mult
  - SimpleAdd.vm
  - SimpleAnd.vm
  - SimpleNeg.vm
  - SimpleOr.vm
  - SimpleSub.vm
  - SimpleEq.vm

test_files:
  - SimplePopTemp.vm
  - SimpleLt.vm
  - SimpleGt.vm
