site_name: "Bits e Processadores"
theme:
  custom_dir: "theme"
  name: active-handout
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.tabs.link
    - content.code.annotate # (1)
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

docs_dir: "docs-src"

site_url: https://insper.github.io/bitsEprocessadores/
edit_uri: "edit/docs/docs-src/"

repo_name: "Insper/bitseproc"
repo_url: "https://github.com/insper/bitseproc"

copyright: "Copyright &copy; Rafael Corsi @ insper"

extra_css:
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-css@main/devlife.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js

plugins:
  - search
  - active-exercises:
      offering_id: 1

extra:
  ihandout_config:
    #    calendar: /active-handout/reference/calendar/calendar.yml
    #    counter:
    #      - question
    #      - tip
    #      - exercise
    #      - example
    report:
      api-base: https://127.0.0.1:8080/api/offerings/1/
      url: https://127.0.0.1:8080/api/offerings/1/exercises/

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:

nav:
  - Home:
      - "index.md"
      - "Sobre.md"
      - "Sobre-Criterios-de-Avaliacao.md"
      - "Sobre-Rubricas.md"

  #- 'Util-Aulas.md'
  #- '21a/Avaliacoes.md'

  - "Projetos":
      - "class/intro-projeto.md"
      - "class/comb-projeto.md"
  #  - 'LogiComb-Projeto.md'
  #  - 'ula-Projeto.md'
  #  #- 'ula-Projeto-dicas.md'
  #  - 'seq-Projeto.md'
  #  - 'assembly-Projeto.md'
  #  - 'F - CPU':
  #      - 'cpu-Projeto.md'
  #      - 'cpu-Testando.md'
  #  - 'assembler-Projeto.md'
  #  - 'vm-Projeto.md'
  #  - 'J-VMtranslator-Projeto.md'
  #  - 'X-Processadores-Projeto.md'
  #
  - Labs:
      - "class/intro-benchmark-lab.md"
      - "class/intro-lab-1.md"
      - "class/intro-lab-2.md"
      - "Lab 4: Transistores/ CI": "commum-content/labs/A-Transistores-Lab-1.md"
      - "class/comb-lab-1.md"
      - "class/ula-lab-1.md"
      - "class/ula-lab-2.md"
      - "class/seq-lab-1.md"
  #  - 'ula-Lab-1.md'
  #  - 'ula-Lab-2.md'
  #  - 'ula-Lab-3.md'
  #  - 'seq-Lab-1.md'
  #  - 'assembly-Lab-1.md'
  #  - 'assembly-Lab-2.md'
  #  - 'assembly-Lab-3.md'
  #  - 'assembly-Lab-4.md'
  #  - 'assembly-lab-HW.md'
  #  - 'ula-lab-4.md'
  #  - 'cpu-lab-1.md'
  #  - 'Lab 16: Assembler':
  #    - 'assembler-Lab-1.md'
  #    - 'assembler-Lab-1-parte-1.md'
  #    - 'assembler-Lab-1-parte-2.md'
  #    - 'assembler-Lab-1-parte-3.md'
  #    - 'assembler-Lab-1-parte-4.md'
  #    - 'assembler-Lab-1-parte-5.md'
  #  - 'vm-Lab-1.md'
  #  - 'Lab 18: VMtranslator':
  #    - 'VMtranslator-Lab-1-old.md'
  #    - 'VMtranslator-Lab-1.md'
  #
  - Teoria:
      - "commum-content/teoria/Teoria-Dados.md"
      - "commum-content/teoria/Teoria-Algebra-Booleana.md"
      - "commum-content/teoria/Teoria-CMOS.md"
      - "commum-content/teoria/Teoria-RTL.md"
      - "commum-content/teoria/Teoria-Componentes.md"
      - "commum-content/teoria/Teoria-Aritmetica-Binaria.md"
      - "commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md"
      - "commum-content/teoria/Teoria-ULA.md"
      - "commum-content/teoria/Teoria-Logica-Sequencial.md"
      - "commum-content/teoria/Teoria-Sequencial-Componentes.md"
      - "commum-content/teoria/Teoria-Z01.md"
      - "commum-content/teoria/Teoria-Assembly.md"
      - "commum-content/teoria/Teoria-Z01-mapadeMemoria.md"
      - "commum-content/teoria/Teoria-nasm-jump.md"
      - "commum-content/teoria/Teoria-Linguagem-de-Maquina.md"
      - "commum-content/teoria/Teoria-Assembler.md"
      - "commum-content/teoria/Teoria-Assembler-SymbolTable.md"
      - "commum-content/teoria/Teoria-vm.md"
      - "commum-content/teoria/Teoria-vm-segmentos.md"
      - "commum-content/teoria/Teoria-vm-jump.md"
      - "commum-content/teoria/Teoria-vm-funcoes.md"
      - "commum-content/teoria/Teoria-vm-memoria.md"
      - "commum-content/teoria/Vídeo Aulas (Luciano)": "Util-Video-Aulas.md"

  - MyHDL:
      - "teoria/myhdl-1.md"
  #
  #- 'VHDL':
  #  - 'VHDL-basico.md'
  #  - 'VHDL-Combinacional.md'
  #  - 'VHDL-port-map.md'
  #  - 'VHDL-Sequencial.md'
  #  - 'VHDL-RTL.md'
  #  - 'VHDL-exemplos.md'

  - "Z01":
      - "Resumo Assembly": "commum-content/z01/z01-Resumo-Assembly.md"
      - "Z01.1 Cheat Sheet": "commum-content/z01/z01-Cheat-Sheet.md"
      - "Instruction Set": "commum-content/z01/z01-InstructionSet.md"
      - "Resumo VM": "commum-content/z01/z01-Resumo-VM.md"

  - Estudo:
      - "commum-content/exercicios/Exercicio-Algebra-Booleana-1.md"
      - "commum-content/exercicios/Exercicio-Algebra-Booleana-2.md"
      - "Dados Digitais - 1": https://docs.google.com/spreadsheets/d/1rN_zQqYaVI8PjAhKqEBCmY-_06I0X9dD0RddcI-miJs/edit?usp=sharing
      - "commum-content/exercicios/Exercicio-Dados-2.md"
      - "Handout Aritmetica Booleana": https://github.com/Insper/elementos-bits-content/blob/main/exercicios/Exercicio-Aritmetica-Booleana.pdf
      - "Lógica Sequencial": "https://forms.gle/XMsFCDMYsmz1qUP86"
      - "Linguagem de Máquina": "https://github.com/Insper/elementos-bits-content/blob/main/exercicios/Linguagem_de_maquina.pdf"
      - "commum-content/exercicios/Exercicio-CPU-1.md"
      - "commum-content/exercicios/Exercicio-CPU-2.md"

  - Útil:
      - "commum-content/util/Util-Comecando-novo-projeto.md"
      - "commum-content/util/Util-vixi-sou-scrum.md"
#
#- História:
#  - 'Historia-linux.md'
