test_files:
- add
- sub
#  - mov 1000
#  - abs 1000
#  - max 10000
#  - mult    10000
#  - mod     10000
#  - div     10000
#  - pow     10000
#  - factorial    10000
#  - stringLength 2000
#  - isEven       1000
#  - palindromo   1000
#  - vectorMean   2000
