name: ci
on:
  push
  
# Environment
env:
  CI: true
  PYTHON_VERSION: 3.x

jobs:
     
  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

      # Checkout source form GitHub
      - uses: actions/checkout@v2
      - run: |
          git submodule update --init --recursive

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: |
          pip install -r requirements-mkdocs.txt

      - run: |
          mkdocs gh-deploy --force
          mkdocs --version
